POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "mahirali",
    "email": "sshadab@gmail.com",
    "password":"Shadabali"
}

###
GET http://localhost:3000/users


###
DELETE http://localhost:3000/users/5e58813c6d42c4311442dfe7


### 
POST http://localhost:3000/task HTTP/1.1
content-type: application/json

{
    "description":"Taks is not Comp",
    "completed": "false"
}
###
GET http://localhost:3000/tasks

###
GET http://localhost:3000/tasks/5e59cbfe0972a20d6459940b
